// Import the formatISO9075 function from the date-fns library for formatting dates in ISO 9075 format
import {formatISO9075} from "date-fns";

// Import the Link component from react-router-dom to create navigational links
import {Link} from "react-router-dom";

// The Post component receives several props like _id, title, summary, cover, content, createdAt, and author from the app, use google inspect to see
// all except createdAt from our "timestamps: true" in models/Post.js in the backend and "_id" which is autogenerated, is sent to the app from our /Post api endPoint in the backend
export default function Post({_id, title, summary, cover, content, createdAt, author}) {

  return (
    <div className="post"> {/* Wrapper div with the class 'post' */}
      
      {/* Image Section */}
      <div className="image">
        {/* Clicking on the image links to a specific post using the post "_id", this "_id" will be referenced as ":id" in ./app.js, it is auto-generated by mongodb for the post */}
        <Link to={`/post/${_id}`}>
          {/* The image src is dynamically generated by appending the cover file path */}
          <img src={'http://localhost:3001/' + cover} alt=""/>
        </Link>
      </div>

      {/* Text Section */}
      <div className="texts">
        {/* Title links to the same post */}
        <Link to={`/post/${_id}`}>
          <h2>{title}</h2> {/* Display the post title */}
        </Link>

        {/* Info Section: author and createdAt date */}
        <p className="info">
          {/* Display the author's username */}
          <a className="author">{author.username}</a>
          {/* Display the formatted creation date */}
          <time>{formatISO9075(new Date(createdAt))}</time>
        </p>

        {/* Display the summary of the post */}
        <p className="summary">{summary}</p>

      </div>
    </div>
  );
}
